name: "Update financial dashboard"

on:
  push:
    paths:
      - "automation/finanse/*"
      - ".github/workflows/finance.yaml"

jobs:
  dashboard:
    runs-on: ubuntu-latest
    name: Update financial dashboard
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Update dashboard
        run: |
          cd automation/finanse
          nix build
          cp result ../../layouts/shortcodes/finanse.html
          nix flake check
          git add ../../layouts/shortcodes/finanse.html
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4.15.3
        with:
          commit_message: Automated financial dashboard snapshot
